#!/usr/bin/env python3
"""Build a sanitized static ops report for GitHub Pages (no customer PII)."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DEFAULT_SOURCE = ROOT / "ops-report-source.html"

SANITIZE: list[tuple[str, str]] = [
    ("Service Commercial Cisco", "Sales Queue East"),
    ("Service Commercial Webex", "Support Queue East"),
    ("CX Assist Service Sales Paris", "CX Assist Sales East"),
    ("Service Client Paris", "Client Services AA"),
    ("Excecutive Pegulu", "Executive Line"),
    ("Andre's Home Office", "Remote Office 1"),
    ("Alejandra Gonzalez", "Casey Rivera"),
    ("Jeremie Pegulu", "Alex Morgan"),
    ("Adam Van Rooy", "Jordan Lee"),
    ("Charles Nzioka", "Riley Park"),
    ("Garima Sharma", "Sam Chen"),
    ("Peter Green", "Taylor Brooks"),
    ("Dan Wallace", "Morgan Quinn"),
    ("Joyce Mayaka", "Jamie Ortiz"),
    ("Jeremie Desk", "Agent Desk 1"),
    ("758982e6-3d6e-4379-a363-c8e13ab8f51f", "00000000-0000-0000-0000-000000000000"),
    ("/Users/konyebin/Documents/GitHub/wxops/docs/", "data/docs/"),
    ("Paris", "East Region"),
    ("+91", "+XX"),
    ("May 24 – Jun 23, 2026", "Apr 1 – Apr 30, 2026 (demo)"),
    ("Apr 20 – May 18, 2026", "Apr 1 – Apr 30, 2026 (demo)"),
    ("Your Organization", "Acme Demo Corp"),
]

DEMO_BANNER = """
<div id="demo-banner" style="background:#FEF3C7;border-bottom:1px solid #FCD34D;color:#8a5700;padding:10px 16px;font-size:13px;text-align:center;font-weight:600;">
  📊 Static demo dashboard — sample metrics only, not a live customer report.
  <span style="font-weight:400;margin-left:8px;">Built from the wxops misc ops report template.</span>
</div>
"""


def sanitize(html: str) -> str:
    for old, new in SANITIZE:
        html = html.replace(old, new)
    html = re.sub(
        r"<title>.*?</title>",
        "<title>Webex Calling — Operations Report (Demo)</title>",
        html,
        count=1,
    )
    if 'id="demo-banner"' not in html:
        html = html.replace(
            "<body>",
            f"<body>\n{DEMO_BANNER.strip()}\n",
            1,
        )
    html = re.sub(r"Generated by WxOps", "Demo · GitHub Pages", html)
    return html


def main() -> None:
    parser = argparse.ArgumentParser(description="Create sanitized ops report for GitHub Pages")
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--dest", type=Path, required=True)
    args = parser.parse_args()

    if not args.source.is_file():
        raise SystemExit(f"Source HTML not found: {args.source}")

    html = args.source.read_text(encoding="utf-8")
    out = sanitize(html)
    args.dest.parent.mkdir(parents=True, exist_ok=True)
    args.dest.write_text(out, encoding="utf-8")
    print(f"Wrote {args.dest} ({len(out):,} bytes)")


if __name__ == "__main__":
    main()
